# This file contains the configuration for the project
artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/iamram33z/data-sets/raw/refs/heads/main/winequality-red.zip
  local_data_file: artifacts/data_ingestion/wine_quality_data.zip
  unzip_dir: artifacts/data_ingestion/wine_quality_data
