# This file contains the configuration for the project
artifacts_root: artifacts

# Data ingestion configuration
data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/iamram33z/data-sets/raw/refs/heads/main/winequality-red.zip
  local_data_file: artifacts/data_ingestion/wine_quality_data.zip
  unzip_dir: artifacts/data_ingestion/wine_quality_data

# Data validation configuration
data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/wine_quality_data/winequality-red.csv
  STATUS_FILE: artifacts/data_validation/status.txt
  all_schema: artifacts/data_validation/all_schema.json

# Data transformation configuration
data_transformation:
  root_dir: artifacts/data_transformation
  input_data: artifacts/data_ingestion/wine_quality_data/winequality-red.csv
  train_data: artifacts/data_transformation/train_data.csv
  test_data: artifacts/data_transformation/test_data.csv

# Model training configuration
model_training:
  root_dir: artifacts/model_training
  train_data: artifacts/data_transformation/train_data.csv
  test_data: artifacts/data_transformation/test_data.csv
  model_name: random_forest_model.joblib

# Model evaluation configuration
model_evaluation:
  root_dir: artifacts/model_evaluation
  model: artifacts/model_training/random_forest_model.joblib
  test_data: artifacts/data_transformation/test_data.csv
  metrics_file: artifacts/model_evaluation/evaluation_metrics.json
  model_name: random_forest_model.joblib
  evaluation_metrics: artifacts/model_evaluation/evaluation_metrics.json
  mlflow_uri: "https://dagshub.com/iamram33z/wine-quality-prediction-webapp.mlflow"